version: '3'
services:
  mongo:
    image: mongo
    container_name: test_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db
    ports:
      - 27019:27017
  mongo-express:
    image: mongo-express
    container_name: test_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
volumes:
  mongo_db: {}
