name: crm-demo
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libnsl=2.0.0
  - libsqlite=3.43.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.2
  - pip=23.2.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.1.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - annotated-types==0.5.0
      - anyio==3.7.1
      - black==23.7.0
      - click==8.1.7
      - dnspython==2.4.2
      - exceptiongroup==1.1.3
      - faker==19.6.0
      - fastapi==0.103.1
      - h11==0.14.0
      - httptools==0.6.0
      - idna==3.4
      - mypy-extensions==1.0.0
      - numpy==1.25.2
      - packaging==23.1
      - pandas==2.1.0
      - pathspec==0.11.2
      - platformdirs==3.10.0
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pymongo==4.5.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - six==1.16.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - tomli==2.0.1
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uvicorn==0.23.2
      - uvloop==0.17.0
      - watchfiles==0.20.0
      - websockets==11.0.3
